[build-system]
requires = ["setuptools>=77.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pemfc"
version = "0.0.1"
description = "PEM Fuel Cell Stack Simulation Model"
readme = "README.md"
authors = [
    { name = "Lukas Feierabend", email = "lukas.feierabend@gmail.com" },
]
requires-python = ">=3.9"
license = "MIT"
license-files = ["LICENSE"]
keywords = []
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Operating System :: OS Independent",
]
dependencies = [
    "matplotlib>=3.8.0",
    "numpy>=1.26.3",
    "scipy>=1.11.4",
    "porous_two_phase_flow @ git+https://github.com/lufire/PorousTwoPhaseFlow.git@a5d6f9a41e49e2f0a49fa8ccb35f444cb87c8949"
]

[project.optional-dependencies]
test = [
    "build>=1,<2",
    "pytest>=8,<9",
]

# Auto-discover packages (like find_packages)
[tool.setuptools.packages.find]
include = ["pemfc*"]

# Include package data (similar to include_package_data=True)
[tool.setuptools]
include-package-data = true

[project.urls]
Homepage = "https://github.com/ZBT-Tools/pemfc-core"
Repository = "https://github.com/ZBT-Tools/pemfc-core.git"
Issues = "https://github.com/ZBT-Tools/pemfc-core/issues"
